name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
        
    # Install modules    
    - name: Unit Test
      run: npm install
      
    # Execute unit tests    
    - name: Unit Test
      run: npm run test
